---
root: true
env:
    browser: true
    node: true
    es6: true
overrides:
    - files:
      - "*.jsx"
      - "*.js"
parserOptions:
    ecmaVersion: 2021
    sourceType: "module"
    ecmaFeatures:
        globalReturn: false
        impliedStrict: true
        jsx: true
plugins:
- "react"
extends:
- "eslint:recommended"
- "plugin:react/recommended"
settings:
    react:
        version: "detect"
rules:
    linebreak-style:
    - "error"
    - "unix"
    quotes:
    - "error"
    - "double"
    semi:
    - "error"
    - "always"
    comma-dangle:
    - "error"
    - "always"
    indent:
    - "error"
    - 2
